[project]
name = "c2c-monitor"
version = "0.1.0"
description = "c2c monitor script"
requires-python = ">=3.10"

[project.optional-dependencies]
dev = [
    "ruff",
    "pre-commit",
    "pytest",
]

[tool.ruff]
line-length = 88
exclude = [
    ".git",
    ".venv",
    "__pycache__",
]

[tool.ruff.lint]
select = ["E", "W", "F", "I", "B", "C4", "UP"]
ignore = ["E501"]
fixable = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["F401", "F811"]

[tool.ruff.lint.isort]
known-first-party = ["c2c_monitor"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-v"
